### ISSUE TITLE
Success and fail functions firing upon success or failure

### ISSUE THREAD

**Issue by Wittner** [le717/microajax#1]
Hi,

I'm just integrating your script and it seems that upon success or failure, two of the possible functions are called, success and fail. I've been in and looked at your script which seems to be trapping readyState and looking for a 200 response and then firing off one of the options based on the results. So, I see how it's supposed to work but not why it doesn't. Here is your code in my app. It is wrapped in a 'sync' function. It's supposed to go out and GET a JSON encoded list from my server. Your script successfully returns the JSON data and produces the '4' readyState and 200 success response but still fires the two callbacks.

```javascript
...
syncRecords = function() {
		microAjax({
		  url: "http://localhost/blah/downloadfiles.php",
		  method: "GET",
		  success: ajaxSuccess,
		  warning: ajaxWarning,
		  error: ajaxError
		});
	},

	ajaxSuccess = function(message) { // This gets fired
		console.log('yay, success');
		console.log(message);
	},

	ajaxWarning = function(message) {
		console.log('Just a warning');
		console.log(message);
	},

	ajaxError = function(message) {// This gets fired
		console.log('uh-oh, something went badly wrong!');
		console.log(message); // This is line 134 below
	};
...
```

Console shows:
app.js:133 uh-oh, something went badly wrong!
app.js:134 undefined
app.js:124 yay, success
(and the results from the Ajax call)

**Comment by le717** [comment]
Huh, this is interesting. Not sure why this would be happening. I'll try to look at it today. :)

**Comment by le717** [comment]
Oops, wrong button. Sorry about that.

**Comment by Wittner** [comment]
Thanks Ie717. The downloaded ajax file is relatively big so I thought it might be some sort of async js problem but I changed the api to just give back a single object with one element and it did the same. Might still be some sort of async problem though - maybe the functions are firing before they realise that success/fail has already happened?

**Comment by le717** [comment]
I am pretty sure I found the issue. I was calling the error handler at all times rather than only at `onerror`. Whoops. Try it now using [this flile](https://raw.githubusercontent.com/le717/microajax/issue-1/microajax.js) and tell me if it works.
